item {
  id: 1
  name: 'cards'
}


item {
  id: 2
  name: 'dice'
}


item {
  id: 3
  name: 'key'
}


item {
  id: 4
  name: 'map'
}


item {
  id: 5
  name: 'phone'
}


item {
  id: 6
  name: 'spider'
}
